FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

EXPOSE 80
EXPOSE 443

# copy everything and build the project
COPY /src
RUN dotnet restore bbt.gateway.messaging/*.csproj
RUN dotnet publish bbt.gateway.messaging/*.csproj -c Release -o out

# build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "bbt.gateway.messaging.dll"]
