FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

RUN adduser -u 5679 --disabled-password --gecos "" smsgateway-workeruser && chown -R smsgateway-workeruser:smsgateway-workeruser /app
USER smsgateway-workeruser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false

COPY ["bbt.gateway.worker/bbt.gateway.worker.csproj", "bbt.gateway.worker/"]
RUN dotnet restore "bbt.gateway.worker/bbt.gateway.worker.csproj"
COPY . .
WORKDIR "/src/bbt.gateway.worker"
RUN dotnet build "bbt.gateway.worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "bbt.gateway.worker.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000
ENTRYPOINT ["dotnet", "bbt.gateway.worker.dll"]
